version: '3.8'

services:
  afen-app:
    build: .
    container_name: afen-app-dev
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm start"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env